### ISSUE TITLE
[WIP] Medical Updates

### ISSUE THREAD

**Issue by DavidKeaton** [CleverRaven/Cataclysm-DDA#10655]
### Intro

Okay, so I closed the PR and reopened this as an issue. Some comments on @narc0tiq 's thread about scrapes and bruises sort of gave me some ideas where I want this to go.
(beep boop calling @KA101 because `u r mad dope son`)

Any and ALL comments welcome!
### Briefing

My first notion is to abstract the notion of underlying anatomical 'systems' into a class that can be derived from. In said class, any arbitrary number of arbitrary `groups` of `anatomical_parts` can be together. So if you have 2 legs, 2 hands, 2 arms, a sweet eye patch, a hangover, and no dignity; most of these can theoretically be listed in this class. I have setup the very basics of it, along with a notion of design (a modicum I assure you, not an overzealous person or anything). I plan on migrating to JSON loadable files so these 'parts' and 'groups' can be super _dope_ and expanded upon easily. Each `anatomical_part` falls into one or more `anatomical_group`s . These groups I hope to be expandable with the help of either/both Lua or JSON, or black magic I ain't judgin'. 

So parts fall into groups, groups can provide flags to what these parts do. For an example of the slice of my code thus far...

```
enum anatomical_function {
    // motor functions
    AF_AMBULATION = 0,                          /* orthostasis, ambulating, etc */
    // five senses
    AF_OCULAR,                                  /* sight */
    AF_OLFACTORY,                               /* smell */
    AF_AUDITORY,                                /* hearing */
    AF_GUSTATORY,                               /* taste */
    AF_TACTILE,                                 /* touch */
    // circulatory
    AF_RESPIRATORY,                             /* breathing */
    AF_NEUROVASCULAR,                           /* nervous [+ vascular] system */
    AF_CARDIOVASCULAR,                          /* heart & vascular system */
    // chassis, engine, and driver
    AF_SKELETAL,                                /* bones */
    AF_MUSCULAR,                                /* as it says */
    AF_NEUROLOGICAL,                            /* brain/nervous system */
    // non-humanoid functions
    AF_ANTENNAE,                                /* sensory perception via antennae */
    num_af
};
```

So with these `functions` lumped together with both `parts` and `groups`, you could have specific effects or diseases target these systems. 

OR MAYBE I AM OVERTHINKING THE `functions` PART A BIT, I DUNNO, BRAINSTORMING AND STUFF.

So what this roundabouts would look like further implemented, is things you have to watch for. Do you want to go into v-tach? _Nah dawg, you don't. So stop sniffing coke son._

Been overdoing the stimulants for a fair amount, and have taken some cardiac damage? _You gun die son._

Oh man, you have gone and broke that finger. _Guess you can't blap blap now._

Happen to have cut your fingertip too much with a knife, guess you goin'ta have some scar tissue son, _guess you are._

Okay so maybe it won't get _that_ crazy, but I would like a decently dynamic medical system, so it is more than just "chug vitamins, don't do drugs, use first aid kit, done." Broken bones should be a reality before arm health reaches zero, more limbs and appendages should be a thing _anyway_ (hell maybe we could spin that off for mutated `anatomy`)! _GASP SON_
# EAST COAST (aka `updates`)
- I am still very much in the design area for this, and trying to clean up old branches at the same time. I am way too weird about leaving open old branches. Can't just keep making things I'll make and not do them!
### TODO
- [ ] Implement `anatomy` for creatures/critters/players/space-monsters/etc.
- [ ] JSONify the `anatomy` aspects a bit, so as to make adding new `parts` and whatnot is legit as hell.
- [ ] Implement new UI to better fit how _baller_ this update will be.
- [x] Realize that I am mad baller and fly as hell. Damn you sexy. 
- [ ] ~~Play way too much Cataclysm~~ Implement vital signs (BP, MAP, O2%)
- [ ] Do the Hospital terrain some justice.
- [x] I am sexy as hell and _ballin' hard_, and so can you.
##

**Comment by BFG1992** [comment]
Well, it's possibly will be very hard for devs to code...
But it looks **TOTALLY FUCKING AMAZING**.
I am strongly for it. Because of... well, EVERYTHING you wrote here.

**Comment by i2amroy** [comment]
I think a lot of the feasibility of this design comes down to the nitty-gritty exact implementation level. If it can be implemented in a way that is easy for the players to see, easy for the modders to handle in json, and easy for future developers to understand then I don't see a problem with implementing something like this. It just happens that it's a lot of work and a all three of those facts depend on your exact implementation.

**Comment by DavidKeaton** [comment]
Yeah, it's going to be quite the task for sure, and JSON heavy tie-ins is what I am aiming for. I think a LOAD of your `effects` implementation will be SUPER nice in this, but I will still require rolling my own J[SON] for this.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
