### ISSUE TITLE
Magazines, outstanding issues

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#15244]
## Outstanding issues
Summary all of all outstanding magazine issues and where I'm up to with them. It might be helpful if we could start tagging those issues separately and you could mention @mugling when submitting them?

### Reloading

- ~~Reloading of liquids is broken (#15224 and #15200)~~ **[MERGED]** 

- ~~Reloading can fail when inventory is full (#15079)~~ **[MERGED]**
   Posssible fix is #15084 but we might want to make this more targeted and suspend checks only
   for `ACT_RELOAD` as opposed to all player activities.

- ~~Can reload spilled liquids from map (#15241)~~ **[MERGED]**
   Currently testing, will push branch shortly

- Misleading colours in inventory (#15122). **[HAVE FIX]**
   Where is the code which draws the inventory screen found?

- ~~Automation of reloading in some cicumstances (#15185)~~ **[MERGED]**
   Anything more than an ugly hack requires refactoring of `*::reload` and `item::pick_reload_ammo`

- Equivalent ammo does not stack if differs in damage status (#15230) **[DISCUSS]**
  Should we be supporting different damage states for ammo and batteries in the first place?
  Is the current behavior reasonable or should it be changed?

### Usage

* ~~Unexpected shortage of ammo `debugmsg` (#15028, #15240).~~ **[MERGED]**
   Turrets remain functional. I'm not especially familiar with the vehicle code but possibly
    an easy fix if someone else is?

* ~~NPCs dont understand reloadable guns (#15088)~~ **[MERGED]**
    Temporary fix could be for them to use weapons with `item::magazine_integral() == true`
    Long-term depends upon refactors in `*::reload` and `item::pick_reload_ammo`

### New content

* ~~Various issues/PRs for new content including~~ (#15213, #15143, #15062) **[MERGED]**

### Miscellaneous

* Ammo doesn't burn in magazines (#15185) **[NEEDS VALIDATION]**
    Does it burn in containers? Not sure if this issue is restricted to just magazines.

* ~~Single loading weapons and round in chamber~~ (#15172) **[DISCUSS]**
    The former yes, once all existing bugs resolved, the latter is of questionable benefit for the
    considerable extra code complexity. We should definitely support part-loading of magazines.

* Craftable magazines (#15166) **[DISCUSS]**
    See `doc/GAME_BALANCE.md`

## Plan

- [X] Test and merge #15192 deprecating magazine mods to aid refactoring

- [X] Next rebase #15217 and convert all existing guns to use new magazine format.

- [X] Merge #15124 and use this when adding further magazines

- [X] Following #15192 refactor `::*reload` and `item::pick_reload_ammo` into multiple smaller functions

- [X] Use these functions to provide automation of some reloading tasks

- [ ] Fix reloading times, especially for large stacks

- [X] Have NPCs use provided functions

**Comment by Rivet-the-Zombie** [comment]
>Misleading colours in inventory (#15122). [NEED HELP]
Where is the code which draws the inventory screen found?

I found code that governs item name color in [item.cpp L:1843](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item.cpp#L1843).

**Comment by mugling** [comment]
Hmm didn't know `character::get_ammo` existing. It also appears to be used by the NPC reloading code. That's helpful to know, thanks @Rivet-the-Zombie

**Comment by mugling** [comment]
I'm working on a refactor of `character::get_ammo` that fixes @Coolthulhu's interface issue (#15122) and splits up `item::pick_ammo_reload` to use this, which should help with #15185 and others. As NPC's also use `get_ammo` this provides the groundwork for closing #15088. This fix doesn't include support for spare magazines and is a merge conflict with #15192 so once that's through I'll push those changes. If anyone is familiar with the NPC code some help with that would be appreciated.

I've migrated all the old magazines in preparation for #15217. Once #15192 is merged the intention is to rebase and then update all the ranged weapons. Unfortunately that PR is consequentially likely to be rather large but unfortunately we have to change all the relevant JSONs in one go when switching to the new format.

**Comment by BevapDin** [comment]
Regarding reloading from ground: the character should only pick up as many charges as can be used for reloading (can be an estimation, doesn't need to be the exact value). Grabbing the whole stack can cause pain from being overburdened. Easily visible with charcoal, which is quite heavy.

Similar issue with unloading: the ammo gets dropped when the character can not carry it because of the weight, but at the time of the check, the ammo is still contained in the item and is included in the currently carried weight. It's basically applied twice.

> Equivalent ammo does not stack if differs in damage status (#15230) [DISCUSS]

Does reloading (and unloading) ammo keep the damage status and does the damage status affect the ammo when being fired? Should it?

If not, there is no difference between damaged and undamaged ammo and there is no point in allowing ammo to be damaged at all. It should either ignore the damage (not display it and merge stacks) or not accumulate damage at all.

**Comment by mugling** [comment]
> Does reloading (and unloading) ammo keep the damage status

Yes

> does the damage status affect the ammo when being fired?

No

> or not accumulate damage at all.

This would greatly simplify the interface and subsequent to #14839 is easier to implement.

> Regarding reloading from ground: the character should only pick up as many charges as can be used for reloading

Needs work in `item_location::obtain`, probably a defaulted parameter specifying number of charges and/or maximum volume to grab. The latter might be a bit cleaner.

> Similar issue with unloading ... the ammo is still contained in the item and is included in the currently carried weight. It's basically applied twice.

I want to look at refactoring the menu from `player::wield` into `player::dispose_item` or something equivalent so this can be done as part of this.

**Comment by DeadLeaves** [comment]
There are also still quite a few weapons that need magazines. I can think of M1A and the MP7 for example. Don't know if they're from a mod or not since everyone hated the idea of way to see what mod an item comes from.

**Comment by mugling** [comment]
@DeadLeaves. There's a lot more to convert. #15217 makes this easier by moving each converted gun to the appropriate subdir once conversion is done (or deemed unnecessary for items with integral magazines)

**Comment by DeadLeaves** [comment]
Alright, It's just that I didn't see anything about it in OP. Anyway, I found another bug when playing just now with the new reloading interface. 
https://gyazo.com/ac7fac000f5753470a2d460e0db3119a
All ammo seem to have 0 in all stats. I'm fairly sure that is not what is supposed to be displayed.

**Comment by mugling** [comment]
> All ammo seem to have 0 in all stats. I'm fairly sure that is not what is supposed to be displayed.

Looks like a bug, can you open an issue?

**Comment by DeadLeaves** [comment]
Ill do it once I'm done playing. I decided I'm gonna stop trying to figure stuff out and just enjoy the game for once.

**Comment by mugling** [comment]
#15217 is now complete and includes all **existing** guns that used magazines updated to the new format. Some obvious alternative magazines are specified (eg. `usp45mag <--> usp9mag`) but we can revisit this later after #15177.

**Comment by joneskun** [comment]
A7 laser rifle (and probably others) can't be unmodded/modded after using it once "You should unload your x before modifying it"

**Comment by mugling** [comment]
#15401 closes the latest non-duplicate bug-reports.

Next up is #15315 which presently depends upon #15398

**Comment by chaosvolt** [comment]
It appears that non-magazine-using ranged weapons now crash when attempting to reload. Tested in builds 4422 and 4428.

**Comment by chaosvolt** [comment]
Glorious bug comment removed because I done derped. Instead, have some typos.

AKM Magazine: Description mentions AK-74M instead of AKM. I'm assuming this one was a fail on my part.
Saiga-12 Box Magazine: No period at end of description.
Saiga-12 Drim Magazine: Same as with the box mag.
STEN Magazine: "based of the magazines" Based off, based on, or based off of would sound better. My bad.
AK-74M Magazine: No period at end of description, this one's likely my fault.

**Comment by Rivet-the-Zombie** [comment]
The M in magazine shouldn't be capitalized either.

**Comment by chaosvolt** [comment]
Hmm? In which? I was capitalizing those just for the sake of list clarity, not directly citing the proper display names.

**Comment by Rivet-the-Zombie** [comment]
I seem to recall some of the Ms in 'magazine' being capitalized, but that's likely been fixed already.

**Comment by chaosvolt** [comment]
Seems to have been, yes.

**Comment by mugling** [comment]
> Glorious bug comment removed because I done derped.

translation?

**Comment by chaosvolt** [comment]
> translation?

I'd posted a comment previously referencing https://github.com/CleverRaven/Cataclysm-DDA/issues/15462, then removed it after the underlying pre-existing issue was fixed.

**Comment by chaosvolt** [comment]
Leave the typo fixes to someone else.

**Comment by mugling** [comment]
Pretty much all of these issues are resolved and those which aren't have their own tagged issues
