### ISSUE TITLE
 Mod Inclusion Project

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#24699]
A new project to review and potentially absorb mods into the core DDA game. Outlined in the [Projects page](https://github.com/CleverRaven/Cataclysm-DDA/projects), and a [development process](https://github.com/CleverRaven/Cataclysm-DDA/projects/18) to evaluate mods and their appropriateness to become inducted into the vanilla game.

### Project Scope
Since this is the first issue for the community, this is the project goal:
>Project dedicated to reviewing and evaluating the various creations in official mods (\data\mods) and unofficial mods that may be appropriate for inclusion into the core experience/game.

>Ideally, any official mods that are included wholesale would be designated obsolete in the modinfo.json to avoid duplications, but also to recognize the efforts of the original author(s)/maintainer(s).

>Additionally, this focuses the energy of contributors and CleverRaven developers into generating and fixing core content, rather than redirecting efforts to consistently fix issues that arise in external mods with major changes in core DDA experience.

### Methodology
This is the methodology that I have outlined (open for discussion and change):
- Review official mods alphabetically via Issue for discussion (what should / should not be added, any changes to fit core DDA experience, is author approval necessary/given?)
- Induct mod via single or multiple Pull Requests (dependent upon size of mod, ease of review and testing)
- Obsolete mod if inducted completely (to avoid duplications, errors and any other possible bugs)
- Review what to do with mod if not inducted completely (remove objects that have been added to prevent duplication, leave alone, mark as Obsolete?)
- Main Issue to suggest unofficial mods for induction
- Repeat cycle for unofficial mods

### Reasoning
[During my time in the C:DDA community](https://www.reddit.com/r/Xcom/comments/6ti27k/gdc_of_xcom_2012_art_evolution_and_design/dlu79bt/), I have consistently noticed that modders and contributors tend to err on the side of caution and release their contributions as mods, instead of enduring the rigors of the Pull Request process, for many reasons, but the main one seemingly "get feedback to see if it's good enough for the game". I have also noticed, like many others, that there are a good deal many ideas encapsulated in these mods, that would see far more use and appreciation were they included in the base Dark Days Ahead experience. I have spent a majority of my time attempting to shape an environment of positivity for modding and contributions in the community and pushing for authors and creators to merge their creations for all to enjoy (whether through "fun" gameplay or "!!FUN!!" realism), so I'd like to take the next step towards this process by achieving what has been outlined above. I ask for the GitHub community to assist in this goal through constructive feedback and working towards the destination, to hopefully strive for a better experience for all.

I appreciate the time anyone took to review this material, even if a small portion. Starting tomorrow (after evaluating any feedback by then), the first mod up for review will be Animatronics (essentially review mods in descending order located in \data\mods). Additionally, any of the blacklist are potentially going to be skipped/ignored as that defeats the purpose of this project.

### Order of Review

**Official**
- [x] - Alternative Map Key (skipped, potentially a future feature that can be included in-game as a toggleable option rather than using as an external mod)
- [x] - Animatronic Monsters (skipped per discussion, review for potential removal for obsolete and feature derelict)
- [x] - [Arcana and Magic Items](https://github.com/CleverRaven/Cataclysm-DDA/issues/24733)
- [x] - [Bionics Systems Mod](https://github.com/CleverRaven/Cataclysm-DDA/issues/24780) (Inducted #25369)
- [ ] - [Vehicle Additions Pack (blazemod)](https://github.com/CleverRaven/Cataclysm-DDA/issues/24730) (Modified induction by mlangsdorf)
- [x] - [Boats](https://github.com/CleverRaven/Cataclysm-DDA/issues/24864)
- [x] - Bright Nights (skipped per similar treatment with Crazy Cataclysm, except instead of silly things [like Crazy Cataclysm would accept], anything too "high-tech" or "futuristic" falls under Bright Nights, still open to suggestions in main project issue)
- [x] - [Craftable Gun Pack](https://github.com/CleverRaven/Cataclysm-DDA/issues/24966)
- [x] - Crazy Cataclysm (skipped, as it is somewhat of a catch-all for silly/crazy content not suitable for DDA)
- [x] - [Folding Parts pack](https://github.com/CleverRaven/Cataclysm-DDA/issues/25068) (Partial induction #25815)
- [ ] - [DinoMod](https://github.com/CleverRaven/Cataclysm-DDA/issues/25294) (Limited induction available, see thread for more)
- [ ] - [Icecoon's Arsenal](https://github.com/CleverRaven/Cataclysm-DDA/issues/25444) (Limited induction available, see thread for more)
- [x] - Fast Zombies (skipped, now core feature to alter zombie speeds on world settings, review for potential removal for obsolete)
- [x] - [DeadLeaves' Fictional Guns](https://github.com/CleverRaven/Cataclysm-DDA/issues/25806) (Closed for lack of interest)
- [x] - [Filthy Clothing](https://github.com/CleverRaven/Cataclysm-DDA/issues/26228) (Inducted #29291)
- [x] - Generic Guns (skipped, treatment similar to blacklist mods, counterproductive to add)
- [ ] - [Makeshift Items Mod](https://github.com/CleverRaven/Cataclysm-DDA/issues/26809) (Re-opened by interest)
- [ ] - [Medieval and Historic Content](https://github.com/CleverRaven/Cataclysm-DDA/issues/27092) (Modified inductions #28753, #28744, #28820, #28800, #28851, #29204, still open)
- [x] - [More Buildings](https://github.com/CleverRaven/Cataclysm-DDA/pull/24924) (Induction by cosmiccoincidence)
- [ ] - Classes and Scenarios Mod
- [ ] - More Locations (Modified induction #28192, still open)
- [ ] - More Survival Tools (Modified inductions #28810, #28822, #28910, #28934, still open)
- [x] - Mundane Zombies (skipped, blacklist mod)
- [ ] - Mutant NPCs
- [ ] - Beta National Guard Camp (potentially will be skipped, perhaps more discussion as to completion)
- [ ] - Necromancy
- [x] - No Acid Zombies (skipped, blacklist mod)
- [x] - No Explosive Zombies (skipped, blacklist mod)
- [x] - Perfect Reliability (skipped, treatment similar to blacklist mods, counterproductive to add, review for potential removal for obsolete)
- [x] - No Flaming Weapons (skipped, blacklist mod)
- [x] - No Fungal Monsters (skipped, blacklist mod)
- [x] - No Medieval Items (skipped, blacklist mod)
- [x] - Disable Mutagens (skipped, blacklist mod)
- [x] - Disable NPC Needs (skipped, counterproductive to add)
- [x] - No Antique Firearms (skipped, blacklist mod)
- [x] - Disable Religious Texts (skipped, blacklist mod)
- [x] - Prevent Zombie Revivication (skipped, counterproductive to add)
- [x] - No Fictional Guns (skipped, blacklist mod)
- [x] - No Sci-Fi Equipment (skipped, blacklist mod)
- [x] - No Survivor Armor (skipped, blacklist mod)
- [x] - No Triffids (skipped, blacklist mod)
- [x] - No Zombie Animals (skipped, blacklist mod)
- [x] - Simplified Nutrition (skipped, counterproductive to add)
- [x] - [NPC traits](https://github.com/CleverRaven/Cataclysm-DDA/pull/27170) (Induction by I-am-Erk)
- [ ] - Mythological Replicas
- [x] - No Monsters (skipped, blacklist mod)
- [ ] - Extended Realistic Guns
- [x] - Classic Roguelike Classes (skipped, not suitable for DDA theme, may be appropriate for Crazy Cataclysm)
- [x] - Safe Autodoc (skipped, counterproductive to add)
- [x] - Slow Zombies (skipped, now core feature to alter zombie speeds on world settings, review for potential removal for obsolete)
- [x] - StatsThroughSkills (Inducted; now in-game option due to Lua removal #28637)
- [ ] - [Tanks and Other Vehicles](https://github.com/CleverRaven/Cataclysm-DDA/issues/24730) (Modified induction by mlangsdorf)
- [ ] - Bens GF recipies
- [x] - Tough Zombies (skipped, now core feature to alter zombie health/resilience on world settings, review for potential removal for obsolete)
- [x] - Urban Development (skipped, still under development)
- [x] - Tall Buildings (Inducted #27412)
- [ ] - Zombie Nightvision

**Unofficial**
(Please recommend suggestions)
Artyom's Gun Emporium (suggested by Jownky)
Cataclysm++ (suggested by Alexandreiah)

**Comment by 0be1isk** [comment]
one mod that should def be mainlined is NPC traits

**Comment by nexusmrsep** [comment]
Good call @DracoGriffin. Personaly I always  wondered why all those nice locations were left for mods. Also @acidia's urban development would be a blast is it will be ever finished under present circumstances.

**Comment by FulcrumA** [comment]
I do like the general idea behind this ticket - there are quite many mods that already are pretty well-fitting and shouldn't be too hard to integrate into base game to make it bigger/better without significantly changing the gameplay and the lore. 

However, as I believe it can easily go awry, I'd be very careful about including mods presenting new themes, 'genres' of items and enemies and other such content.

One of the problem some people have when approaching the game - and something I admit I personally had to get used to - is the "kitchen sink" content CDDA already presents. Zombies, extraterrestrials, extradimensionals, cyborgs, rogue AI, demonic/spiritual entities, fought by player's survivors, mutants, cyborgs using everything from stone age technology, through modern equivalent to hi-tech, improvised and factory-assembled with healthy helping of positively occult in nature artifacts is currently quite much. The skipping of/between themes may detract from enjoyment of some and while currently it's something most still could get more or less used to, adding even more newly-thematic content will IMHO may make the game indigestible.

I'd rather concentrate on quality of life and current features/content-expanding inclusions (for example, expansion of current vehicles to involve water vessels seems like a pretty logical and believable thing - though I'd adjust it first, since Boats mod seems a bit hacky with its boat board "wheels" due to limits it has to follow without adjusting the game's code). 

Many of the mods, be they changes to what's already there, additions of new, balanced items in boundaries of current types of content or disabling of certain features could be easily integrated as optional world settings - but let absolutely new species/types of enemies (especially ones based upon existing franchise), new types of technology (or magitech) and other mods significantly changing the mood of the game and realities of the world of it remain as mods or at the very least be significantly adjusted so the new influences are very subtle and fit well with content already existing (for example, given demonic and lovecraftian influences, extradimensional creatures, cults and mysterious artifacts - a very subtle, hard to notice and reliably utilize addition of mostly-fluff occultism could mesh well with what we have, but outright providing players with D&D-like magical spells would be something I'd look for a mod for so I can get rid of it).

Pardon for lengthy comment, just thought I'd point it all out as something to keep in mind as while I'd like the game expanded and many mods better integrated, I certainly want to avoid significant changes to the basic realities of CDDA as I know it.

**Comment by Cyrano7** [comment]
I think we should just let this process happen naturally like we have been doing for years. If you look back to the beginning a lot of content in the game was in a mod first, then mainlined once someone willing to do the work came along or it reached a fully developed state. Examples Extended Cataclysm or More Survival Tools(which was partially mainlined).

**Comment by DracoGriffin** [comment]
>I think we should just let this process happen naturally like we have been doing for years. If you look back to the beginning a lot of content in the game was in a mod first, then mainlined once someone willing to do the work came along or it reached a fully developed state. Examples Extended Cataclysm or More Survival Tools(which was partially mainlined).

I agree, however there are a ton of abandoned mods (although the real concern stems from all the abandoned "official" mods that lack maintainers) that could be merged into the base game and not have to worry about resolving issues or problems with those mods anymore. This now acts as somewhat of a wavering approval (not broad acceptance of everything but allows secondary examination of perhaps items/objects/locations/missions/NPCs/enemies/etc that may have been denied previously but could potentially be acceptable now); as well as acting as a beacon for others to see "Oh hey, they are willing to accept that stuff, I could do that", rather than "Eh, I dunno if they'll want that and I don't want to get rejected after working on all of that".

Secondly, the main part of this Issue is to discuss and further refine how best to approach this (already detailed above) as the plan is to move forward already. Further, this can be a useful approach for new contributors to get their feet wet and do some of the tons of "busywork" that is very often ignored or sidelined by core developers/contributors in efforts to focus on new features/resolving serious bugs/infrastructure development.

At any time kevin wishes to pull support on this project, I am willing to part ways with it. In the meantime, I'd like to see what can be folded in.

**Comment by MT-Arnoldussen** [comment]
@0be1isk I second NPC traits (and mutations), but they are not without issues. I know of #24535, and I'm sure there are more.

**Comment by FulcrumA** [comment]
@MT-Arnoldussen 
I personally witnessed issues between it and disabling of NPC needs in the past as per  #23715

**Comment by Night-Pryanik** [comment]
Animatronics. Animatronics monsters don't thematically fit into the Cataclysm setting, so they wouldn't fit for mainlining.
Furthermore I think the mod shouldn't be "officially" bundled with the game. It's just one of these mods that just adds some new random content - in this case it's just a set of monsters and one location. 
Overall I prefer to get rid of this mod from the list of "official" mods bundled with the game.

**Comment by nexusmrsep** [comment]
> Animatronics. Animatronics monsters don't thematically fit into the Cataclysm setting, so they wouldn't fit for mainlining.

Though @DracoGriffin wanted to discuss each mod in a separate issue, I'll share my opinion too. I agree with @Night-Pryanik , but I believe it should be merged/ported to Crazy Cataclysm Mod - animatronics are kind of wacky addition, so they would fit well there. And they would be a nice random-encounter style of addition CCM needs. And also it would de-bloat official mods list.

**Comment by DracoGriffin** [comment]
>I agree with @Night-Pryanik , but I believe it should be merged/ported to Crazy Cataclysm Mod - animatronics are kind of wacky addition, so they would fit well there. And they would be a nice random-encounter style of addition CCM needs. And also it would de-bloat official mods list.

That's actually an extremely good idea, especially moving forward. Thank you for the idea. Will be using it.

**Comment by mlangsdorf** [comment]
I would prefer to have content in the main game, where developers and modders are aware of it. Exclusion mods are easy to write for people who don't want something in the game.

I'd really rather see all of Crazy Catalysm mainlined, and then add a standard mod to exclude the content.

**Comment by kevingranade** [comment]
The rationale for, "mainline, but keep as a mod" is to allow shared
maintenance of mod content (i.e. a simple search of the repository will
find instances of json entities that need to be changed if the entity type
is updated, as well as allowing unit tests to load and test mod content)
without burdening the game with the overhead of loading every game entity
defined in a mod.
That overhead comes both in the form of code support for things like
handling conflicting item definitions until they can be resolved by a
blacklist mod or exclusion directive and sheer resource usage from loading
a ton of mod content, only to unload it afterwards.
It's much more efficient to load mods on demand.

Data:
Core json is currently 319,000 lines of json, and mod content includes
231,000 lines, inlining that mod content would roughly double game load
time, which is basically never going to be ok.  In fact that strongly
indicates to me that we should be going in the other direction, breaking
the current core dda content into multiple mods, but maintaining some of
them as "core mods" that are loaded by default.
Only if someone wants a specific subset of core + mod content should things
like blacklist mods come into play.

**Comment by DracoGriffin** [comment]
>In fact that strongly indicates to me that we should be going in the other direction, breaking the current core dda content into multiple mods, but maintaining some of them as "core mods" that are loaded by default. Only if someone wants a specific subset of core + mod content should things like blacklist mods come into play.

Should the "copy-from" project take precedence in this case? I'm just not entirely sure on how useful that would be on reducing game load time.

If that doesn't reduce that strain, then this project and issue are majorly counterproductive.

However, if the need is to compartmentalize DDA into several, smaller core subsets/mods, that could be quite challenging unless it's more superficial (aka, splitting all vehicle stuff into one mod, all mutations and items in another, etc) at which point it becomes more of a categorical problem ("what should go where, and what should go with what") than a balancing act ("if core mod D isn't used, then players shouldn't be able to do Y").

And just to clarify, I simply listed all the official/bundled mods as a roadmap, none of the blacklist mods will be considered (I hope that's obvious, I also added short remarks for each entry).

**Comment by Night-Pryanik** [comment]
> Fast Zombies (skipped, now core feature to alter zombie speeds on world settings, review for potential removal for obsolete)
> Slow Zombies (skipped, now core feature to alter zombie speeds on world settings, review for potential removal for obsolete)

Fast and Slow Zombies change the speed only for zombies, while in world option we are altering the speed of all monsters altogether.

> Tough Zombies (skipped, now core feature to alter zombie speeds on world settings, review for potential removal for obsolete)

The same here for resilience. By the way, there's a typo: it's not a `speed` in description, but a resilience.

**Comment by DracoGriffin** [comment]
>The same here for resilience. By the way, there's a typo: it's not a speed in description, but a resilience.

Fixed, thanks. I was a bit overzealous in copy and paste.

Although you are correct about the mods only affecting zombies, they are still marked obsolete: true, so majority of players will never know of their existence. However, this may still be useful if that was changed back to false, but again, what happens if a player reduces both world settings speed and activates slow/fast zombie mod? Which overrides or is it combined?

Furthermore, what is the rationale behind retaining obsolete mods other than retaining backwards compatibility or is that the only reason? Is that potentially open to change?

**Comment by FulcrumA** [comment]
Maybe settings could generally be turned more robust, allowing fiddling with stuff like resilience/speed for various generalized monster groups (zombie, animal, extradimensional/nether, extraterrestrial)? It does seem that a lot of many mod functionalities are basically what vanilla game could have with just a small column of settings.

**Comment by Jownky** [comment]
Could Artyom's Gun Emporium be reviewed and evaluated as well? It would be nice to have even more variety of weapons in the game! :D

**Comment by Alexandreiah** [comment]
I would always raise this but shouldnt some parts of cata++ be mainlined already? I do know that some parts of it are REALLY OP, but its not something that CANT be fixed or balanced easely. Also kevin did express some interest into adding more hostile NPC stuff to the game.

**Comment by cosmiccoincidence** [comment]
Adding the "More Buildings" mod will be part 3 of my "Adding Whaley's Locations" process. #24816

**Comment by FulcrumA** [comment]
@Brambor 
>Does the game need to load lab levels until player approaches a lab? No. Does the game need to load a tank json etc. until a player encounters a tank? No.

Yes.
The content of those mods must be loaded for the world to be able to generate them and know how to handle them in the first place. Sure, the levels itself shouldn't be generated till they're not approached - but that's exactly how game already works. The data regarding existence of labs, however, must be loaded so the game will know that there should be levels - and what levels would those - that'd be accessible in a particular location.

>There is a lot of time when a human player doesn't use the full CPU and RAM power, such as when idly 'watching' the game menu.

That's also already how it is! The loading screens should very well inform you that the mods and general in-game content is loaded only upon starting/loading the game, not when you're in the main menu.

**Comment by Brambor** [comment]
@FulcrumA 
> The content of those mods must be loaded for the world to be able to generate them and know how to handle them in the first place.

Well, for many the case could be that they are not required on game load which could be specified. For example, when a world is generated, then 'pack' Boats doesn't need its json yet, because it doesn't affect world generation because the 'pack' doesn't have any structures vehicles etc. to generate. I'm talking mainly about first world generation rather than loading save, but even there adjustments can be made such as load only required 'packs', so do not load Boats if there is none - that might sound weird, it might be untrue or complicated.

I'm sure there are or can be optimizations so it shouldn't be such an issue to double json files.

**Comment by FulcrumA** [comment]
@Brambor 
Correct me if I am wrong but does it merely mean that Boat json for designs won't be loaded because they're not any? In general, the mod still has to be loaded so the game has loaded recipes for boat elements and can recognize such elements. There's no difference there. Same with items, enemies etc - at least some of the mod has to be loaded for the game to recognize the possibility of mod content's existence, even when not loading particular instance of it.

**Comment by kevingranade** [comment]
> I believe that the game could include mods and loading times could be improved by optimization such as not load content that is not strictly needed. Does the game need to load lab levels until player approaches a lab? No. Does the game need to load a tank json etc. until a player encounters a tank? No.

This is possible, but it is also quite difficult and error prone.  I'm not sure you're following my suggestion, which is to break up the core json and refrain from loading it *if the player has decided they do not want that content in their game*.

**Comment by cake-pie** [comment]
Is there a way to be notified when certain mods come up for review/discussion, or do we just have to keep an eye out for it?

**Comment by FulcrumA** [comment]
>Is there a way to be notified when certain mods come up for review/discussion, or do we just have to keep an eye out for it?

I was wondering about that myself. Probably would be wise if this ticket would send an alert as Draco makes a comment linking to new discussed mod ticket and then deletes it, to repeat with another.

**Comment by Human-Shield** [comment]
So do blacklist mods reduce load time or are the items still loaded and then ignored?

**Comment by kevingranade** [comment]
Yes, in the current system, we load everything, then the blacklist removes it. We do even more work when something is blacklisted than if it isn't.

**Comment by Feuerhai** [comment]
As of #29291 filthy clothing has just been mainlined.

**Comment by DracoGriffin** [comment]
> As of #29291 filthy clothing has just been mainlined.

Added and updated original comment with all the recent additions.

**Comment by Throwaway-name** [comment]
What's the status of Roguelike Classes post-Magiclysm?

**Comment by kevingranade** [comment]
This has run it's course and been stale for many months now.
