### ISSUE TITLE
It's C++14 time

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#27690]
New features keep piling up in the C++ standards, and when we can, we want to start using them.

**Describe the solution you'd like**  
It looks like we're unblocked (and have been for a while) to adopt the C++14 standard.

**Describe alternatives you've considered**  
Wait some more, which is a viable option if people are using a build that doesn't support c++14 yet.

**Additional context**  
See the [C++14 support matrix](https://en.cppreference.com/w/cpp/compiler_support#cpp14), in particular:
* GCC 5.1
    * Code::Blocks 17.12 ships with a TDM-GCC version incorporating GCC 5.1 see [C::B Downloads](http://www.codeblocks.org/downloads/26)
    * [Debian Stretch](https://www.debian.org/releases/stable/amd64/release-notes/index) ships with GCC 6.
* Clang 3.4
    * XCode is based on Clang 3.4 or later as of Xcode 5.1 based on a [random gist I found](https://gist.github.com/yamaya/2924292).
* MSVC 2015 (2017?).

** TODO **
- [ ] Elicit feedback on people's compiler versions.
- [ ] Update Jenkins build system to use a c++14 supporting compiler version.
- [ ] Update documentation to specify new minimum compiler versions (see above).
- [ ] Edit travis.yml to use different compiler versions.
- [ ] Update [Homebrew Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cataclysm.rb)

** Cool stuff **
~~std::optional would supplant cata::optional. (no functional increase, but it would be a little cleanup)~~
~~std::string_view may present opportunities for improvement in the json parser and anywhere else that handles many strings.~~
~~The filesystem library will allow unification of POSIX and windows filesystem code.~~
Holy crap all of those were C++17 features >_<
std::quoted() may improve some serialization code.
std::make_unique can clean up some code.
user-defined literals for standard library types might be useful
compile-time integer sequences can replace some static int arrays and might have some perf benefits.
Higher version of cross-compiler version might have addressed the std::to_string problem.
Higher compiler versions tend to emit faster code, so that would be a non-standards based benefit.

**Comment by ralreegorganon** [comment]
Probably worth putting verifying/updating [the CDDA Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cataclysm.rb) for c++14  on the checklist here for someone to tackle, since I think it's one of the primary way macOS players get their copy.  Based on [the PR that last updated it](https://github.com/Homebrew/homebrew-core/pull/30837) it looks like @vircung did that last.

**Comment by Treah** [comment]
@ralreegorganon are there still 2 different compile methods for mac? kinda remember when I used to keep that up to date that there was a brew one and another one using native stuff. May need to check brew and confirm its using a C++14 compliant compiler.

**Comment by ifreund** [comment]
Yeah there seem to be.  I just have my fork of the git repo cloned and compile very similarly to how you would on any other unix like os.  It seems that the the current brew formula still works.  You can either install 0.C with `brew install cataclysm` which downloads a binary or have brew compile the latest experimental with `brew install cataclysm --HEAD`.

I did get one warning compiling on macOS 10.14 although the game launched and ran without issue.
```
Warning: cataclysm dependency libmodplug was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
```

You can see analytics on download/build stats [here](https://formulae.brew.sh/analytics/)

One thing I noticed is that there doesn't seem to be an option to compile without tiles, which should probably be added.  

The advantage of the brew formula is that it requires very little knowledge to successfully compile and run the latest experimental, even if it is a bit slower/less configurable .

I don't really know much about brew formulas, but I assume that changing 11 to 14 [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cataclysm.rb#L28) would be all that's needed.

**Comment by jbytheway** [comment]
Mostly done once #30427 is merged, but someone will still need to test / update the homebrew recipe.  I'm not in a position to do that.

**Comment by ifreund** [comment]
I can do that, I PR'd something over there before.

**Comment by ifreund** [comment]
Looks like the homebrew build didn't really need to be brought up to c++14, as the `ENV.cxx11` was apparently vestigial.  Removed that and tweaked the formula a bit in https://github.com/Homebrew/homebrew-core/pull/39740
