### ISSUE TITLE
Martial Arts Rebalance

### ISSUE THREAD

**Issue by Hymore246** [CleverRaven/Cataclysm-DDA#32422]
**Is your feature request related to a problem? Please describe.**  
I am in the process of performing doing a complete rebalance of the martial art styles in CDDA. There is a lot I will be changing and I am creating this issue to track all the associated PRs. I've also included a small FAQ to answer some question people might have about the rebalance.

**What will you be changing in this rebalance?**

- I will be making adjustments to almost every martial art style in the game. Some martial arts are overperforming and need to be nerfed. Others are underdeveloped and need to be expanded upon. 
- I wanted to give different playstyles to as many martial arts as possible. This is difficult given how martial arts work in CDDA but having unique gameplay or gimmicks will help make combat more involved and let the styles stand out from one another. 
- I will also be adding a few new technique attributes such as "stunned_target", "powerful_knockback", and "take_weapon" just to name a few. I also created a new buff type, OnPause that is used by a few styles.
- Also, thanks to #31733 fixing the martial arts duration bug, nearly every buff and technique needs their durations to be updated.

**What are you not doing in this rebalance?**
- I am not making any chances to the way martial arts and techniques are done on the back end. Techniques will still be randomly selected, you can only use one martial art at a time, and so on.
- I am not removing or adding any new styles nor am I moving anything to a mod. This rebalance focuses only on the styles we have right now and whether not something needs moved or removed is beyond the scope of these PRs.
- I will not be changing Debug Mastery or the C.R.I.T. martial arts. Debug Mastery is mainly an Easter egg and isn't meant to be balanced. The C.R.I.T. martial arts will updated by the author in there own update with other C.R.I.T. content.

**What styles are you buffing?**
- Just to name a few: Aikido (fully defense but no more -50% damage debuff), Capoarie (has kick techs, moving unlocks stronger kick techs), Karate (new passive buff, 2 new techniques), Tai Chi (added a few new buffs including the new OnPause buff). Lizard Kung Fu is now a full style with techniques and buffs that utilize walls like originally intented. 
- Most styles are getting tweaks to make them function better overall which could be consider a buff too.

**What styles are you nerfing?**
- Just to name a few: Zui Quan (duh), animal Kung Fu styles (no longer have the +80% of a stat to damage passive buff), Medival Swordmanship (high damage output is reduced).
- I should also point out that even if I nerf a style, I'll still try to give it something more reasonable to work with. For example, Zui Quan gives you +3 Dodge attempts instead of +100 but 2 of them now come from an OnMove buff.

**How will you be adding all these changes to the game?**
- So, it's pretty clear by now that I am changing a lot and adding a bunch of new stuff. Trying to do this in a single PR is going to be a massive headache to merge. Instead, I will be creating a seperate PR for each martial art (30 in total). I will create them one at a time in order to give people time to read, react, offer opinions, etc. This means it is going to take a while for everything to be added to the game but I think this is the safest way to do this. New mechanics will be added with the first style that uses them. For example, Dragon Kung Fu will come with the code to implement  the "downed_target" and "stunned target" attributes. I will be updating this issue with the status of the PRs so people have an easier time to tracking the rebalance.

I will be doing the PRs in alphabetical order. Below is a list of the martial arts I'll be changing and their merge status.

- [x] Aikido (#32423)
- [x] Bionic Combatives (#32540)
- [x] Boxing (#32664)
- [x] Brawling (#32773)
- [x] Capoeria (#32847)
- [x] Centipede Kung Fu (#32951)
- [x] Crane Kung Fu (#33015)
- [x] Dragon Kung Fu (#33093)
- [x] Eskrima (#33173)
- [x] Fencing (#33210)
- [x] Fior Di Battaglia (#33261)
- [x] Judo (#33448)
- [x] Karate (#33510)
- [x] Krav Maga (#33602)
- [x] Leopard Kung Fu (#33810)
- [x] Lizard Kung Fu (#33872)
- [x] Medival Swordsmanship (#34017)
- [x] Muay Thai (#34070)
- [x] Ninjutsu (#34135)
- [x] Niten-Ichi Ryu (#34182)
- [x] Pankration (#34252)
- [x] Panzer Kunst (#34324)
- [x] Scorpion Kung Fu (#34407)
- [x] Silat (#34479)
- [x] Snake Kung Fu (#34574)
- [x] Sojutsu (#34654)
- [x] Taekwondo (#34711)
- [x] Tai Chi (#34790)
- [x] Tiger Kung Fu (#34847)
- [x] Toad Kung Fu (#34925)
- [x] Viper Kung Fu (#34986)
- [x] Wing Chun (#35085)
- [x] Zui Qaun (#35144)

**Comment by LaVeyanFiend** [comment]
You should probably ping the new styles' authors if you want to know who wants to be included in the rebalance.

List of authors:

Fior: DemAvalon
Panzer: Photoloss
C.R.I.T.: Soupster89
Wing Chun: Mposes2k

**Comment by Hymore246** [comment]
> 
> 
> You should probably ping the new styles' authors if you want to know whose work wants to be included in the rebalance.
> 
> Reference List of authors:
> 
> Fior: DemAvalon
> Panzer: Photoloss
> C.R.I.T.: Soupster89
> Wing Chun/Mainlined version of Medieval Swordsmanship: Mooses2k

That's a good idea. I reached out to Mooses2k and DemAvalon on discord. Photoloss hasn't been active since the end of may and Soupster89 looks like he was doing his own up date to C.R.I.T. with #31090. Considering those styles are in mods, it might be better to leave them as is.

**Comment by sammy202020** [comment]
just a small thing. i dont think swordsmanship needs changed right now. the high damage output is mostly from that weapons it can use 

also think you should only buff the stuff you want to buff instead of nerfing some stuff also just so we can see post change if those fightings you want to nerf still are way to strong. i say this because i really dont like as a player seeing massive changes in the meta over a single update. so maybe break the nerfs and buffs into to things just incase things end up being balanced post buffing

**Comment by Hymore246** [comment]
I'm breaking up the updates by style and I'm not planning on doing more than one at a time. So this will be at least 30 different updates which is why I made this issue. This is going to be a long process and there will be plenty of time to see how the changes affect the game.

**Comment by communistkiro** [comment]
Why would you want to even martial arts out, when in reality they are nowhere equal in the number of techniques, or in their performance against other martial arts? If you want to game-ify it- make it '''balanced''', whatever that means to whomever- there's a lot of other more pressing issue that need rebalancing. Without armor penetration and only bash damage, unarmed MA are useful for single-to-few unarmored targets, or with high enough stats a mob, but not of, say, armored zombies.

What I think needs rethinking is armor penetration values (currently all null) on the higher or highest techniques. Otherwise your Huge, Insanely Strong, Tough char is going have to not use his unarmed and melee skills when he switches to some other killing method that's reliable.

**Comment by TychaiosIlithios** [comment]
Tbh not sure what to answer because what's written is 'gonna change some to + and some to -' without actually pointing to functional goal behind changes.

What I loved about old martial arts was the separation of goals behind them:

shaolin styles - generally NOT so good melee techniques taken to support relatively early gameplay of a character, complimenting a specific statset to ignore lack of skill. Later far less useful. Whole idea is to have stat buff and not so much cool techniques later.

styles like karate, boxing, capoeira - more or less midbalance for early characters, lasting okay-ish into midgame. 

aikido/judo - more or less defensive style for certain situations

centipede/zui quan - pro fighting styles for crowd extermination by really strong characters that don't even need techniques much.

viper and scorpion - cheat styles when you want blood on ceilings.

The only style that imho is too cheesy without openly stating that it's a cheat is silat - cuz crits and dodge and stun and many weapons.

--
So since I can't understand what you exactly intend to change, would like to ask to consider not just linear balancing of martial arts, but maybe functional groups:
1) stat assisted newbie arts for points that are either not available or too hard to find in books early. For those who want their perception geeks to snake it through grabber zombie.
2) cheap to buy/easy to find early martial arts that do not get extreme edge later
3) arts for high levels of martial and dodge, providing buffs from successes, never static
4) defensive arts

Lastly just wanted to say that am currently modding 5) niche arts for specific weapons - likely the weapons that work badly without said arts. And biggest brainxploding problem is not to even out damage with others but to actually make it somehow different from others without inventing chuck.

**Comment by NickGrease** [comment]
If you've made it to this comment without looking at Hymore246's first PR, Aikido (#32423), do yourself a favor and take a look. It describes the goal of the martial art, the problems it currently has, and clear, straight forward solutions in a format that is both easy to read and understand. If the remaining 29 PR's are of the same standard, I don't think there's much to worry about.

I'm not a mind reader, but I don't get the impression that the goal of this sweeping list of PR's is to make all martial arts 'even', but to fix the broken parts and try to differentiate the various styles. 

Best of luck Hymore246!

**Comment by Hymore246** [comment]
I've talked to DemAvalon and got permission to update Fior Di Battaglia. I couldn't reach Mooses2k but I did find a message from him on Discord that said I could include Wing Chun in the rebalance if I wanted.

I couldn't find Photoloss or Soupster89. They appear to be inactive right now so I will not be including Panzer Krust or the C.R.I.T martial arts in the rebalance.

**Comment by Contemplator11** [comment]
If possible, would you be so kind to take a closer look at Brawling, which currently can be used with any weapon (if I'm not mistaking) and quarterstaff (iron-shod as well)? A quarterstaff is an integral part of martial arts originating from Okinawa, such as Karate.

**Comment by anothersimulacrum** [comment]
Brawling is on the list, and will be the next one that he looks at.

**Comment by Soupster89** [comment]
Hello! I have been inactive lately, and I see that you are rebalancing the various martial arts that CDDA has. It is all very applaudable and I like the breadth you are giving them.

Forgive me if I sound uncaring in my request, I am not the best at grammar.

I have no problems if you would like to propose changes to my files. I am having difficulty adjusting them in a way that stays true to their base intent without being overpowered as they currently are too strong even after the recent melee changes passed.

I am also on the CDDA subreddit under u/Soupster89 if you would like to PM me.

Thank you in earnest.

**Comment by Hymore246** [comment]
> 
> 
> Hello! I have been inactive lately, and I see that you are rebalancing the various martial arts that CDDA has. It is all very applaudable and I like the breadth you are giving them.
> 
> Forgive me if I sound uncaring in my request, I am not the best at grammar.
> 
> I have no problems if you would like to propose changes to my files. I am having difficulty adjusting them in a way that stays true to their base intent without being overpowered as they currently are too strong even after the recent melee changes passed.
> 
> I am also on the CDDA subreddit under u/Soupster89 if you would like to PM me.
> 
> Thank you in earnest.

Sounds good! I've sent you a message on Reddit so we can chat about the martial arts in your mod.

**Comment by LaVeyanFiend** [comment]
Weapon arts time! 😄

**Comment by ZhilkinSerg** [comment]
Please consider https://github.com/CleverRaven/Cataclysm-DDA/issues/23696 when rebalancing.

**Comment by ZhilkinSerg** [comment]
Also #25859 if you mind.

**Comment by Hymore246** [comment]
The martial arts rebalance is now complete! I'll be keeping my eye on the martial arts system for a bit to make sure no bugs pop up. Thank you everyone for your support and feedback.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/fantasy-based-martial-arts/25178/2
