### ISSUE TITLE
Magiclysm bugs

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#32546]
# Describe the bug
Several small bugs found while testing Magiclysms new stuffs. I don't want to open issues for each one.  So feel free to close this if it makes tracking difficult.

- [ ] Frost Armor does nothing.  I don't think those are valid values for effects.  Maybe it's there for future work.  Same with environmental protection.
- [ ] Grotesque boost has unnecessary values.  The second value in an effect array is for resistance.  Maybe it was assumed to be a range for random numbers.
- [x] Traits grant additional level of spell.  A profession with 10 will grant a spell at level 10.  A trait with 10 grants a spell at level 11. (Fixed by #32553)
- [x] Spell casting items show the ID instead of name.  `magic_missile` instead of "Magic Missile." (Fixed by #32553)
- [x] Spell casting items give an error if you don't know the spell.  Should either have no error or do nothing, depending on the intent.
- [x] Wands are not foci.
- [ ] Spells, in player UI, are alphabetized by ID instead of name, so `druid_rootstrike` shows up as Rootstrike next to the other D spells.
- [ ] Cone of Cold doesn't cause cold air.  Adding fields to spells works, so the values just need to be adjusted.  It might produce something, but it wasn't enough to show up with the temperature visualizer. 
- [x] Monsters can be summoned on top of NPCs. Causes minor visual bugs: eg. NPC is invisible for some time. (Fixed by #32553)
- [x] Rounds no longer exist.   I think.   Time should be displayed in moves, seconds, minutes etc.  That might be something outside this mod.
- [ ] Bless doesn't work as AOE.  Not sure why.  It works on one target, self, but not others in the AOE.
- [ ] NPCs don't react to effect spells. If you give an NPC magic-ebola or something, they should get mad.  maybe add a flag, or use the good/bad rating of effects?

# Versions and configuration
 - OS: Windows
 - Graphics version: Tiles
 - Mods loaded: Magiclysm

# Additional context
Bugs aside, I like it.  Always appreciate new toys for modders.

**Comment by KorGgenT** [comment]
> Rounds no longer exist. I think. Time should be displayed in moves, seconds, minutes etc. That might be something outside this mod.

what does this mean? what is it in reference to?

> Spell casting items give an error if you don't know the spell. Should either have no error or do nothing, depending on the intent.

This is already fixed in the current version.

**Comment by SunshineDistillery** [comment]
I thought the 6-second round was removed in favor of 1-second rounds.  In the display for a spell's duration, it shows times in rounds, which is not necessarily meaningful to a player. 

Pretty minor.  It may be fixed already; I only update about once a week.

**Comment by KorGgenT** [comment]
no it shows in "turns" which is analogous to seconds.

**Comment by FuelType-Memes** [comment]
> 
> 
> no it shows in "turns" which is analogous to seconds.

But seconds are much more informative than turns. Maybe convert turns to seconds and then to minutes and so on? So in the UI it says "cast time: 1 min 30 sec" instead of "90 turns"?

**Comment by KorGgenT** [comment]
Except for one very important thing: casting time is affected by your
character's speed. So if you cast a spell that takes three turns and you
have a move speed of 200, it will take you one and a half seconds

**Comment by foulman** [comment]
Some of these are probably valid, I think a couple of spells ended up having a mess in them due to my sloppy development "environment", Frost armor being one, I think the actual spell might have been deleted or overwritten by my early json toying around and github learning curve. There was some material lost with a PR at least one time. I plan on going through them and taking care of anything messy like that, including making nature's bow working more like a bow due to some code improvements.

**Comment by foulman** [comment]
Wands are not foci at present, I didn't see the point in doing that since I can't even enforce you having to wield them to use them in the first place. When there's a flag that I can set that requires you to wield an object to activate it, I'll certainly put it on them.

**Comment by Leland** [comment]
Updated description to move to checkboxes, marked off the items handled by @KorGgenT in #32553

**Comment by KorGgenT** [comment]
I'm going to close this issue and reopen a frost armor issue. the rest of the things in the list seem to be feature requests or not really bugs
