### ISSUE TITLE
Items with "turns_per_charge" property don't last long enough

### ISSUE THREAD

**Issue by DaviBones** [CleverRaven/Cataclysm-DDA#33192]
# Describe the bug

Predictably, ever since the turn length was altered from 6 seconds to 1, items with turns_per_charge property (mostly light sources AFAIK) don't last nearly long enough. I tested this with the oil lamp and glowstick, but presumably others are affected as well.

# Steps To Reproduce

1. Spawn a character and cheat in an oil lamp and 0.5L of lamp oil.
2. Fill the lamp with oil and switch it on.
3. Wait for 3 in-game hours.
4. The lamp will run out of fuel after ~2.8 hours.

# Expected behavior

In real life, 0.5L of lamp oil will last about 34 hours (source: https://www.redhillgeneralstore.com/Oil-Lamp-Parts/Lantern-Oil.htm )

This fix could be as simple as multiplying all the "turns_per_charge" values in the JSONs by 6, thus returning them to their previous behavior. Alternatively, we could take this opportunity to come up with more accurate numbers -- for example, for the oil lamp, a turns_per_charge value of 240 matches the numbers I retrieved from the above link.

# To-Do list
Stuff that probably doesn't need changes:
- Explosives use ```turn_per_charge``` but seem fine (fuse times of 1-10 seconds for grenades, 1-2 minutes for timed bombs)
- Flaming weapons are for fun and have no basis on reality AFAICT so any changes would be rather arbitrary

Stuff that could use a reality check:
- [x] ```candle_lit``` lasts 1.4 hours (Fixed in #33665)
- [x] ```oil_lamp_on``` lasts 4 hours (Fixed in #33665)
- [x] ```glowstick_lit``` lasts 40 minutes (Fixed in #33665)
- [x] ```gasoline_lantern_on``` lasts 2 hours (Fixed in #33665)
- [ ] ```oxylamp_on``` lasts 4 hours with small welding tank
- [ ] ```ref_lighter_on``` lasts 10 minutes
- [ ] ```torch_lit``` lasts 25 minutes
- [ ] ```hobo_stove``` lasts 8 hours
- [ ] ```tinderbox_on``` lasts 16 hours
- [x] ```rm13_armor_on``` lasts 4 hours (Fixed in #33621)
- [ ] ```rebreather_on``` and ```rebreather_xl_on``` last 10 minutes
- [ ] ```mask_h20survivor_on``` and ```mask_h20survivorxl_on``` last 20 minutes
- [ ] ```scuba_tank_on``` last 10 minutes
- [ ] ```small_scuba_tank_on``` lasts 3 minutes
- [ ] ```combatsaw_on``` lasts 15 minutes
- [ ] ```handflare_lit``` lasts 5 minutes

Battery-using stuff that needs ```power_draw``` property:
- [ ] ```cell_phone_flashlight``` lasts 75 minutes
- [ ] ```smartphone_music``` lasts 5 hours
- [ ] ```smart_phone_flashlight``` has both ```power_draw``` and ```turn_per_charge``` properties
- [ ] ```geiger_on``` lasts 15 minutes
- [ ] ```noise_emitter_on``` lasts 10 minutes
- [ ] ```angular_grinder``` lasts 3 hours

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-6301-g3597e0f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by macrosblackd** [comment]
This is known and many items are in the process of being converted to use `power_draw` based on real life examples (which is what is taking so long).

**Comment by DaviBones** [comment]
Looks like this was fixed in #33665.

**Comment by DaviBones** [comment]
Oops, did a search of the JSONs and realized there are still several things that might need tweaking. Updated the OP with the list. Will try to take care of it in a PR in the next few days.
