### ISSUE TITLE
Failing encumbrance updates following #32586

### ISSUE THREAD

**Issue by Petethegoat** [CleverRaven/Cataclysm-DDA#33236]
# Applicable following #32586 

Documenting remaining failing encumbrance cases after my PR is merged.

### Todo:
- [ ] siphoning doesn't fully update encumbrance until the player takes their next turn. (eg, it will show 16 instead of the full 20 encumbrance immediately after siphoning) possibly related to the below:

- [ ] siphoning from a vehicle takes 1 second, and leaves the player with 0 moves.

- [ ] refilling takes a more appropriate amount of time, leaves the player with full moves (starts a new turn correctly), but does NOT update encumbrance properly. apparently it avoids calling `contents_changed` on the container, or otherwise prevents the ENCUMBRANCE_UPDATE flag from being checked or set correctly.

### siphoning vs refilling callstacks to `contents_changed()`

refilling:
called only once, but takes several seconds and somehow fails to to update encumbrance correctly.
```
item::on_contents_changed()
item::fill_with(item & liquid, int amount)
>	veh_interact::complete_vehicle()
>	activity_handlers::vehicle_finish(player_activity * act, player * p)
std::_Func_class<void,player_activity *,player *>::operator()(player_activity * <_Args_0>, player * <_Args_1>)
>	activity_type::call_finish(player_activity * act, player * p)
player_activity::do_turn(player & p)
game::process_activity()
game::do_turn()
```
siphoning:
called multiple times, but takes 1 second and leaves the player on a turn with 0 moves
```
item::on_contents_changed()
item::fill_with(item & liquid, int amount)
>	Character::pour_into(item & container, item & liquid)
>	activity_handlers::fill_liquid_do_turn(player_activity * act, player * p)
std::_Func_class<void,player_activity *,player *>::operator()(player_activity * <_Args_0>, player * <_Args_1)
>	activity_type::call_do_turn(player_activity * act, player * p)
player_activity::do_turn(player & p)
game::process_activity()
game::do_turn()
```

**Comment by Petethegoat** [comment]
Yay! Figured out the refilling half of the problem. `on_contents_changed()` **should** be called twice, once for the tank that's being filled or siphoned, and once for the container that you're using to hold the liquid.

This wasn't happening for refilling because it was calling `tank.fill_with(liquid_inside_your_container)`, which can't update the liquid container as it has no idea what that is. It's easy to fix in this case, as we have a handy reference to the container and can call `on_contents_changed()` manually, but there are other calls to `fill_with()` that don't have the container handy.
I'm not sure how to address those cases, which are likely to be similarly bug prone with regards to updating encumbrance.

**Comment by Petethegoat** [comment]
As part of trying to debug the remaining siphoning issue, I ended up doing a minor refactor of part of the main game loop- https://github.com/Petethegoat/Cataclysm-DDA/commit/0d86fc112e546e3156008827ead2954f4ced5b10

This doesn't actually fix the issue, or hopefully change anything at all. But having `process_activity()` be called in one place instead of two will hopefully make it much easier to find the actual problem.

**Comment by dobbry-vechur** [comment]
ENCUMBRANCE_UPDATE is nowhere in code and data (except for still being defined in data/json/flags.json). This seems to be obsolete now. Closing.
