### ISSUE TITLE
[Organization] Magiclysm Items Checklist

### ISSUE THREAD

**Issue by LaVeyanFiend** [CleverRaven/Cataclysm-DDA#34205]
**Is your feature request related to a problem? Please describe.**  
Magiclysm's content updates need a central # to keep track of items to be added. List will be updated as more ideas flow in & are implemented. Comments suggesting additions are welcome.

 - [x] Basic crafting tools
- School runes for school-specific crafts(#31687)
- Low-level mana infusion and concentration(#32132)
 - [ ] Advanced crafting tools
 - [ ] Magus items
- Potion brewing(#32132)
 - [ ] Animist items
- Voodoo summoning dolls(#32248)
- Tainted health potion, acting as a heal with the potential to kill and being harmful to combat stats (#32248)
 - [ ] Technomancer items(#34727)
 - Batonstaff(name TBD): alternates between baton & staff mode.
 - M47A1 Techno-Medusa: Multicaliber revolver based off the Phillips & Rogers M47 Medusa.
 - Shotgun gauntlet(name TBD): cestus or other unarmed weapon long enough to cover the forearm with the addition of a short barrel shotgun on the forearm. Modern update to the Hidden Gun from Assassin's Creed.

 - [ ] Earthshaper items

 - [ ] Druid items

 - [ ] Biomancer items

 - [ ] Stormshaper items

 - [ ] Kelvinist items

 - [ ] Non-school items

 - Ring of Blades: Summons throwing knives in hand

**Additional context**

@foulman  Approved™ _Process_ checklist for addition of items:

 "Did you create the spells this item uses?"

 "Did you create the items the spell conjures?"

 "Did you fully test the item?"

 "Did you add any weapons created to MA lists?"

"Did you add the recipe for any craftable items?"

**Comment by Moonsabrt** [comment]
Suggestion for shotgun gauntlet
Blast gauntlet?
