### ISSUE TITLE
Explosive chemistry - rework roadmap

### ISSUE THREAD

**Issue by 1n17** [CleverRaven/Cataclysm-DDA#37232]
# Explosive chemistry
#### High-explosives stage
- [x] Added 2,4-DNP and its synthesis recipe #37179
- [x] Added two recipes for phenol synthesis (from acetylsalicylic acid and coal cracking)
- [x] Added TNT and its synthesis recipe #37179
- [x] Added Toluene (found in labs) and Paint thinner (hardware stores etc), usable as toluene substitute, updated supply groups
- [x] Adding explosive oriented book
- [ ] Review of RDX along with its pathway (hexamine)
- [ ] Adding Cheddite (90 AP/10 FO)
- [ ] Adding Amatol (50/50), substitute amatol demolition charges where dynamite now spawns
- [ ] Adding Unigel type dynamite (80 AN/15 NG/5 sorbent) (NG from glycerol, add glycerol as soap byproduct, no storage of NG), add drop to mines
- [ ] Obsoleting of 'classic' dynamite
- [ ] Adding Nitrocellulose, perhaps Nitroguanidine (it will be needed later)
- [ ] Adding Gelignite type dynamite
- [ ] Review of CompB

- [ ] some form of secondary_explosive requirement so device recipes can be created and updated quickly

- [ ] Removal of HMTD recipe
- [ ] HMTD/TATP/DDNP/sulfur nitride based blasting cap recipes

- [ ] Look over ANFO, potentially adding AN granulate (to by found in mines etc) that can be quickly mixed to ANFO

- [ ] Update of existing device recipes
- [ ] Perhaps add new few devices, including some using improvised, primary explosives like TATP

#### Gun propellant stage
- [ ] Realistic silver/mercury fulminate, tin and sulfur based primer recipes that will need to cure
- [ ] Update black powder to modern, realistic AN/AP based black powder curing recipe
- [ ] Realistic 'double' base, NC/NG based, high performance propellant with curing recipe
- [ ] Realistic 'single' base, NC based, classic smokeless gunpowder with curing recipe

- [ ] Way for ammo recipe to inherit Q (deflagration heat) from selected propellant (allowing for single recipe to scale damage depending if factory, DB, 'mixed', SB or black gunpowder is selected and optionally add fouling flag to created round if applicable)

#### Rocketry stage (early draft)
- [ ] SB/DB, APCP propellants
- [ ] removal of spike rocket, major overhaul of remaining devices
- [ ] TBX/EBX compounds (tritonal, hexal, or simply generic secondary + 20% Al powder, FAE) and payloads
- [ ] incendiary payload

**Comment by CorruptInsurance** [comment]
Hey, have you thought of adding the haber process for easy manufacture of ammonia? I have been thinking about it.

**Comment by 1n17** [comment]
Haber process is not something survivor would be able to do, Frank-Caro process is the go to for post-apocalyptic ammonia.

**Comment by I-am-Erk** [comment]
Comments adapted from your PR:
- make sure to familiarise yourself with and appropriately use the chemical tool properties here!
- nothing here should autolearn, and if you can avoid stuffing everything into advchem and labchem and the other existing chem textbooks that would be good. We need a wider variety of recipe books. While someone could work out how to make tnt from a chem textbook, it's not generally that easy to do

**Comment by 1n17** [comment]
> While someone could definitive work out how to make tnt from a chem textbook, it's not generally that easy to do without a guide written up... This isn't something you want to goof up figuring out yourself.

It's not, but generally you would just end up with unfavorable mixture of MNT's,DNT and TNT, unlikely to be catastrophic, if anything going poof rather than boom. What you really wouldn't want to 'wing' is NG and primaries though - one of main reasons that got me started with this rework.

> chemical tool properties

As to new qualities at large, nearly all of them can be improvised to sufficient degree and are tools of convenience, also chemistry set should contain thermometer, litmus paper and small electronic scale to be of any use - for anything really, just overlooking this for now.

> nothing here should autolearn

True, except cheddite and anfo

**Comment by I-am-Erk** [comment]
Even cheddite and anfo. If you hand someone with a general working knowledge of science a pile of chemicals and say "make an explosive", they won't magically know what to mix to make it. Source: I have a master's degree in organic chemistry and I don't know how to do that.

**Comment by I-am-Erk** [comment]
As for the tool properties, until we have the ability for your experiments to go wrong in catastrophic ways, I don't think we should assume survivors are making explosives with low-end jury-rigged analytical tools.

**Comment by 1n17** [comment]
These are not reasonable positions to hold.

A high-school student should be able to tell you that to make a simple explosive you need a strong oxidizer and energy dense fuel in roughly stoichiometric ratios. Then by applying that to ingredient selection available in game one would invent some variation of respective mixtures.

Also I really shouldn't need to point out that overwhelming majority of lab accidents is caused by not following basic safety precautions and procedures, and not by the lack of instrument precision.

Taking all that into account I can only conclude you're exhibiting some cognitive biases here, primarily Maslow's gavel.

**Comment by I-am-Erk** [comment]
In both the threads where we're having this discussion, you're misunderstanding what a tool quality means. If you want to add ingredients to the chemistry set until it's able to do some basic measuring, then you've given it the analysis property. That property represents the ability to do basic measuring as required for scientific precision. Similarly the hammering tool property means you can bash things, it doesn't mean you have a hammer.

If you want to make the argument that you can mix TNT effectively with measuring spoons eyeballing quantities volumetrically and nothing else, go for it. Provide reliable sources to this end. If not, you're describing a need for analysis tools, either the simple analysis tool quality I provided before for both player and recipe writer convenience, or specific tools like a balance scale and thermometer as ingredients for your recipe if you want to be more precise about it.

Just assuming the character has access to tools to this end isn't going to cut it. Claiming I'm specifically attached to some tool when I'm recommending you just point to an intentionally vague categorical tool is fundamentally misunderstanding how this stuff works.

**Comment by tenmillimaster** [comment]
> Realistic 'double' base, NC/NG based, high performance propellant with curing recipe
> Realistic 'single' base, NC based, classic smokeless gunpowder with curing recipe

These have been discussed to death. See: #12655, #13270, #21962, #27132. 

Making nitrocellulose itself is fine, but certainly not gunpowder, double, single, or triple base. CDDA is not interested in modelling that at the *survivor* scale, faction level, sure.

>Just assuming the character has access to tools to this end isn't going to cut it. Claiming I'm specifically attached to some tool when I'm recommending you just point to an intentionally vague categorical tool is fundamentally misunderstanding how this stuff works.

High explosives need vaguely high purity. Synthesis typically yields crude products that need to be purified, not instantly usable materials. Recrystallization, phasing, extraction via columns or other extraction methods need to be done here to get some of these reagents and things done. At the end, you're gonna want to make sure you made the right thing before you stick it in your pipe bombs.

How would you know that the last product you made, idk, silver nitrate, in your glassware left silver residues, and now your mercury fulminate is contaminated with it because you thought you could wash with a weak acid or something?

You wouldn't. Not without checking.

**Comment by 1n17** [comment]
>These have been discussed to death. See: #12655, #13270, #21962, #27132. They will not happen.
> Making nitrocellulose itself is fine, but certainly not gunpowder, double, single, or triple base. CDDA is not interested in modelling that at the survivor scale, faction level, sure.

That is unfortunate, and misguided. Thanks for saving my time before I got there.

> High explosives need vaguely high purity...

Technical grade purity is fine for most, unless it severely affects sensitivity (either way) or performance.


> How would you know that the last product you made...

Pretty bad example, but I'll roll with it. If possibility of contamination can result in unpleasant consequences - I would use disposable glassware, good practice with primaries btw.

**Comment by Zireael07** [comment]
How is saying 'a single person in post-apo conditions cannot make gunpowder' misguided?

**Comment by 1n17** [comment]
Because it's not that difficult to replicate, nor make key components and additives, even going 'from scratch' route, although it would take some time.

**Comment by 1n17** [comment]
> In both the threads where we're having this discussion, you're misunderstanding what a tool quality means. If you want to add ingredients to the chemistry set until it's able to do some basic measuring, then you've given it the analysis property. That property represents the ability to do basic measuring as required for scientific precision. Similarly the hammering tool property means you can bash things, it doesn't mean you have a hammer.

Then I am indeed misunderstanding, because virtually every chemical reaction in game would need a scale, or at least decent graduated measure and a conversion table. And nearly every reaction using heat that isn't self regulating by boiling would need a thermometer.

**Comment by Zireael07** [comment]
Just FYI, unless someone modified the chemistry set heavily in the meantime after I added it, the chemistry set is this: https://en.wikipedia.org/wiki/Chemistry_set

(This should seriously be a comment in the relevant JSON)

**Comment by 1n17** [comment]
> Just FYI, unless someone modified the chemistry set heavily in the meantime after I added it, the chemistry set is this: https://en.wikipedia.org/wiki/Chemistry_set
> 
> (This should seriously be a comment in the relevant JSON)

Recipe definitely does not reflects that. And it would be perfect, making analysis redundant unless needed for its spectrophotometer.
