### ISSUE TITLE
Desert Region - road map and future plans

### ISSUE THREAD

**Issue by LovamKicsiGazsii** [CleverRaven/Cataclysm-DDA#58115]
### Is your feature request related to a problem? Please describe.

The Desert Region mod wasn't initially made for a full playthrough, and turning it into a balanced experience requires some planning and lots of changes.

So to document my list of future plans and to keep track of progress, I am writing down my notes and ideas I have on this project.

### Solution you would like.

**Changes to the core game:**
- [ ] replace trees, flowers, groundcovers, etc. to their regional counterparts wherever its possible/makes sense
- [ ] migrate artificial grass into core files, have them spawn in home improvement and landscaping supply stores as items, create their own construction and deconstruction entries, use them in stadiums, parks (?) and houses
- [ ] create regional layers for solid earth (Z-1) and rock (Z-2 downward)
- [ ] have destroyed terrains set to regional pseudo terrains

**Planned content for Desert Region:**
- [ ] a proper design document

*Locations*
- [x] mesas
- [ ] buttes (map extra)
- [ ] canyons that aren't circular
- [ ] canyon visitor's center
- [ ] abandoned prospector mines
- [ ] oil rigs and refineries
- [ ] solar farms (1x2, 2x3 variant, and a concentrated solar plant)
- [ ] more trailer homes
- [ ] more ranches
- [ ] lettuce, cotton and citrus farms
- [ ] water towers and reservoirs
- [ ] dense fields of cacti
- [ ] desert-specific map extras

*Weather*
- [ ] tweak and optimize dust storms
- [ ] fine-tune regional weather settings to more closely resemble the climate of southwest Arizona

This change will make the desert hospitable. The summer heat will still be a threat, but it's no longer going to boil your insides.  The constant sweating will make it difficult to stay hydrated, which is to be expected in a desert biome.

*Flora*
- [ ] more cacti (e.g. saguaro cacti)
- [ ] yucca plants (e.g. Joshua trees)
- [ ] aloe vera plants, aloe vera gels, and their recipes
- [ ] more xeric decorative plants
- [ ] update regional trees, shrubs, and flowers with desert plants

*Fauna*
- [ ] remove animals that aren't indigenous to / cannot be found in the Sonoran Desert (e.g. bush elephants)
- [ ] overhaul wilderness monstergroups
- [ ] replace some New England animals with their "desert counterparts" (e.g. ant --> fire ant, red fox --> gray fox)
- [ ] termite and antlion nests
- [ ] vultures and their mutations

### Describe alternatives you have considered.

Once I deem Desert Region a finished and polished product, I'll un-obsolete it.  This list doesn't need to be completed for me to call this mod 'done', and similarly, I'll still keep working on it once all entries are checked.

### Additional context

I don't know when this is finished and I don't plan on releasing this before 0.G stable.
