### ISSUE TITLE
0.G Final Push

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#62352]
### We're almost there.

0.G release is taking a long time due in large part to the senior devs all being quite busy IRL. However, we are at the last few stages of the project and the remaining PRs are quite easy to fix. This issue exists just to pin those PRs and bring attention to them.

#### Testing/Review needed:

- [x] #61447 needs testing, if it works it looks like it can be merged.

#### Quick Fixes:

- [x] #56990 is a difficult fix to do properly, but I have proposed a fix for stable only that can remove it from blockers and should be quite easy: basically we can set some static NPCs to have a movement speed of zero. That fixes the immediate issue.
- [x] #53324 should be resolvable with a few lines of JSON.
- [x] Unless someone wants to put a strong push of effort into portal storms to resolve issues like #58023 and #54463, we should probably disable portal storms by default in 0.G-stable, with a mod to re-enable them if desired. Note that the outstanding issues are not all that hard to resolve if someone wants to push on them, but there are enough of them that I don't think they can go into stable as is.
- [x] #3951 is really easy to do, and ancient, and I'm leaving it on blockers because there's no good reason we haven't done it yet. All it needs is someone, even a new contributor, to do it and become a hero who fixed an ancient issue.
- [x] #57480 seems like it should be a pretty simple check in the code.
- [x] #57708 also seems like it should be a pretty simple code safety check.

#### More complex but still accessible:

- [x] #57254 is an NPC AI addition so it's not simple, per se, but I've written up an algorithm that should be the solution to the release blocker portion and AFAIK it shouldn't require a master coder.
- [x] #61423 needs someone to look at the math and propose a fix, which could be me or it could be you! Chances are the fix is not too tough.

#### Need some more information:

- [x] #55322 / #57521 need someone who can do some performance profiling to get to the bottom of it.
- [x] #59657 may not be an issue, needs checking. If still an issue, we may need some janky fixes to get to release.
- [x] #57585 may be manageably easy to fix. If it is not, we can probably remove it from release blockers.

### Not on this list

If there is something you think really needs solving before stable, bring it up in the comments.
There are also some issues we may try to add to the list depending on progress. In particular:
- Monster exclusion zones: In order to help protect quest NPCs, it would be nice to be able to cover faction bases in a monster exclusion zone, a zone where monsters can't path in. This would solve a lot of "quest is now impossible" issues. For now we're not considering it a release blocker but it's quite highly requested.
- NPC go home: NPCs who path out of there safe zones die, and this is a big problem. While turning off portal storms will solve a lot of this, it's still something that should be resolved. Since we do have NPC activity zones, it should be fairly easy to use similar code where static NPCs will return to their start point when they aren't in combat. Again, this is probably not going to be made into a release blocker, but we'd really love to have it for stable.

**Comment by Hirmuolio** [comment]
#62155 to get usable units::power.
Then quick swap in json from writing power in energy to power in power.
It would be very quite annoying if the swap happened after stable (writing power in energy in json was recently introduced so it would be forgotten temporary thing).

**Comment by I-am-Erk** [comment]
@oosyrag are you able to link a few issues for those? Some are definitely blocker candidates (unfortunately)

**Comment by Zireael07** [comment]
Auto-manage Android keyboard is #62247 
Android access to folders is #60740 
Android graphics (row/columns) settings is partially covered in #59850 (note that automatic dpi detection is possible but can be wonky, Godot Engine for Android has issues with it). Note that someone has UI cut off in #54329 which is reminiscent of Godot problems, too
Some other Android port defaults are mentioned in #58280
Android port quickbar/canceling things is also mentioned in #52630

I can't find issues for the memory tile overlay nor the esc/back change to back button anywhere, but they're both reasonable asks.

**Comment by oosyrag** [comment]
My apologies! Wasn't quite fully awake yet when I wrote that, I obviously should have linked the issues. I even had some of them open while writing. Thanks for the assist Zireael.

Regarding graphics settings, I understand it may be technically unfeasible to get perfect optimization of resolution automatically for each device, but there are approaches to alleviate the issue if screen resolution data is available. I'm unfortunately not very familiar with Android and what device information is available to a program. I'll elaborate more in the respective issue. 

The memory tile overlay and ability to bind soft keyboard and escape are my own ideas that I never made issues for. I'll do that shortly, but I also don't actually wouldn't consider them release blockers, more feature request. But I do think the double tap to escape needs to be mentioned somewhere at least, it's pretty important as far as usability goes! Especially for a new user coming in to a stable build.

**Comment by Moth-Tolias** [comment]
> * [ ]  [BUG/Suggestion: Either make trader NPCs NOT investigate sounds or lock them behind reinforced glass. #56990](https://github.com/CleverRaven/Cataclysm-DDA/issues/56990) is a difficult fix to do properly, but I have proposed a fix for stable only that can remove it from blockers and should be quite easy: basically we can set some static NPCs to have a movement speed of zero. That fixes the immediate issue.
> 

[...]

> * NPC go home: NPCs who path out of there safe zones die, and this is a big problem. While turning off portal storms will solve a lot of this, it's still something that should be resolved. Since we do have NPC activity zones, it should be fairly easy to use similar code where static NPCs will return to their start point when they aren't in combat. Again, this is probably not going to be made into a release blocker, but we'd really love to have it for stable.

if the latter was implemented, would that work as a fix for the former?

**Comment by oosyrag** [comment]
#62387 is an issue I opened for requesting esc/back swapped for Android. I'm not confident enough to make this change myself.
#62385 is a pull request to change the default memory tile overlay, which benefits desktop users as well.

I understand changing defaults can be a touchy subject and I won't be particularly devastated if they don't make it in.

**Comment by jfferson** [comment]
one thing auxiliar to "NPC go home", maybe could be danger heat maps, that could be based on the monster locations, threat level, speed and their detection area. Then the same logic used for heat could be used to make the map. For it to work properly the NPC should also project the random movement of the monsters, which would be added to the limits of the map. Then they could try to avoid those when out of safety zone, because it could have some chance to have monsters just about the safety zone, then setting time could still not resolve the deaths, also another option could be to not let them leave altogether. it could also make the NPCs from the player smarter on combats, by allowing to contextualize combat rules according to threat levels

**Comment by I-am-Erk** [comment]
> if the latter was implemented, would that work as a fix for the former?

Not really. NPC go home won't stop them from smashing out windows and wandering into danger zones, it just sends them back after they do. We still need to have several types of safety test that prevent NPCs from wandering insanely into danger

**Comment by jfferson** [comment]
> > if the latter was implemented, would that work as a fix for the former?
> 
> Not really. NPC go home won't stop them from smashing out windows and wandering into danger zones, it just sends them back after they do. We still need to have several types of safety test that prevent NPCs from wandering insanely into danger

you do have a loop on which the NPC verifies the environment, or something similar? I just want to know where it is, in order to try implementing that "danger heat map" that I talked about, or at least adapting NPC behavior if it already exists. You know, I don't want to have spoilers on my gameplay. It could support some addition to behavior

**Comment by I-am-Erk** [comment]
I'm not yet the right person to ask, though I'm strongly considering learning the code for this better. Feel free to bring it up in discord, it's not really on topic for this issue

**Comment by Night-Pryanik** [comment]
Hooray, it seems that all of issues were either fixed or deferred to some later time.

**Comment by I-am-Erk** [comment]
Yup! Still a few left but we're doing great
