### ISSUE TITLE
Roadmap of the Hell's Raiders

### ISSUE THREAD

**Issue by MNG-cataclysm** [CleverRaven/Cataclysm-DDA#63362]
### Is your feature request related to a problem? Please describe.

I'm mainly making this as a way to keep track of my ideas for the Hell's Raiders, but also as a way for discussion, feedback, and brainstorming on expanding the faction as a whole. This is meant to be over the long term.

### Solution you would like.

Current Plan:

- [ ] More bandit-related locations and places for them to spawn, such as new forts, outposts, plantations, drug labs, etc.
- [ ] Some sort of NPC hierarchy, from slaves -> foot soldiers -> capos -> underbosses -> bosses -> commissioners. Their rarity would be based on their standing, with underbosses and bosses only showing up in heavily fortified locations. The top leadership may or may not appear at all in the game.
- [ ] Some meaningful way of joining the Hell's Raiders. Presently, I think of joining by referral through non-hostile members, such as spy rings or stranded foot soldiers. Joining could include shadowy dealings with unscrupulous merchants to gain favor with the faction, but it shouldn't be simple to do or completely RNG-based. 
- [ ] Missions from both common soldiers up to the top leadership. Lower-tier jobs from common individuals could just be a handful of the random missions we have now, while jobs from higher ranking members would be more meaningful escapades, with lots of risk. These could include attacking settlements to conquer them, raiding caravans from other factions, or skirmishing with rival bandits. Less violent jobs could include settling internal disputes, managing slave populations, or making an example of somebody.
- [ ] Some way of rising in status and rank. Currying favor with the higher-ups through dangerous heists or by simply doing lots of small work could give the player an in on new intel, ownership of several slaves, or the sanction to lead their own crew for the faction. Advancement high enough could gain the player operation of an entire fortress or drug lab, with the Raiders getting a portion of the proceeds. Advancement generally shouldn't come though killing someone of the rank you want; there's too few people like that in the world. However, a possible job for the purposes of gaining a title might include killing a wayward member of high status.

### Describe alternatives you have considered.

There's a bunch of different ways to do these sorts of things, but further discussion on which way would be the best should occur below. 

### Additional context

As a note, the Hell's Raiders should not be moral in any meaningful fashion, aside from protecting themselves and their interests. Joining them will include a lot of morally questionable and downright evil things, such as enslaving people, robbing travelers, extortion, racketeering, distributing narcotics, and murder. This will also make a lot of missions for other factions incompletable and include these other factions becoming downright hostile towards you. Inter-factional intrigue that could involve espionage or playing two factions off of one another for your own benefit could occur, but that's another "can of worms", as they say.

**Comment by MNG-cataclysm** [comment]
> I assume you realize that the "rising in rank" point involves things that would require some (probably rather substantial) additions to the faction system. While slaved could presumably be treated just as companions, with the only difference being that the current companions joined willingly, controlling a number of NPCs/companions while being part of a larger hierarchy is not something that has any support currently.
> 
> This is not meant as criticism of the concept, but merely a warning against biting off too much.

While that’s something I’d like to have in the future, that’s not quite what I was planning on doing yet. I was thinking that rank increases would     just open new dialogue options with NPCs, and possibly some new missions.

**Comment by MNG-cataclysm** [comment]
I could also use some help with this, if anyone would like to work on it.

**Comment by Profugo-Barbatus** [comment]
So the whole slaves thing seems to be a strong sticking point and issue in the community, and I'm wondering if maybe it should be approached at a different angle from the ground up again. Perhaps rather than a slavery/discount legion approach to it of captured slave labor with some level of coordination from what should be opportunistic raiders, it could be looked at more from a criminal extortion lens, protection rackets and all that. Rather than beating down survivors they find, shackling them and putting them to farms, they approach smaller groups of weaker individuals trying to survive, and 'come to an arrangement'. A Hells Raider or two hang around on site, bash a few zombie skulls, scare off other bandits, and gather up a sizeable tribute from the locals and whatever work they are doing. Sites that don't agree to this find themselves getting harassed, up to and including being burned out and killed - would have plenty of small scale quest potential, both for the locals or supporting the raiders if we wanted to permit more evil cooperation. If any of the site residents get too unhappy or uppity about the 'tribute', they're more than welcome to leave - But all that waits out there is hungry zombie hordes. There are many people IRL who would rather just tolerate that shitty situation than risk death.

The player may even be able to still interact at these sites at a basic level - The goons there aren't liable to shoot on sight, would probably be interested in trading some of the locals belongings for drugs or weapons, if the player hasn't already developed a negative reputation with them. Core sites like drug labs and raider camps should still be aggressive, along with bandit parties - Extortion is just one arm of their activities, not their main game.

This is pretty much a 30 minute mused out thought, so if its crap just lemme know.

**Comment by MNG-cataclysm** [comment]
@Profugo-Barbatus That is a wonderful idea, I'll have to see about implementing that. Thank you.
