### ISSUE TITLE
[Mini-Project] Horsies

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#64778]
### Is your feature request related to a problem? Please describe.

Horses want change

### Solution you would like.

Extend horses through a list of PR's performed collaboratively by myself and "horse expert" @Armokorguest , further suggestions are welcome, equally I'd love to know about anyone else's relevant PRs in the works

**DONE**
- [x] #65635 Revamp horse farm into a mutable map with new riding gear and additional animal related vehicles 

**IN-PROGRESS**

**TO-DO** (listed roughly in order likely to be implemented)
- [ ] Add more house/stable variants to the horse farm
- [ ] Add riding background, profession(s) and NPC(s) that spawn at the horse farm
- [ ] Horse breeds (implemented in the same way as dog and cat breeds, using monstergroups for spawns)
  - [ ] Megafauna changes to accommodate breeds?
- [ ] Spook alterations and implementation of mount obedience and training (training likely through recipes though minor gains through actual riding would be nice) Add tracking of mount on map.
- [ ] Riding proficiency/ies
- [ ] Trailer/articulated vehicle changes
- [ ] Animal inventory changes (single item removal, adv inventory support)
- [ ] Mutant horses if #63997 or a similar PR gets merged
- [ ] More map variants for the horse farm buildings and more horse related maps (stuff like a harness track w/ casino, large animal vet, rescue centre, riding school etc)

### Describe alternatives you have considered.

Letting the horses stew

**Comment by jiornojiovanni** [comment]
Maybe some way to remember the horse last position? Even tho you can do that with the carriage

**Comment by PatrikLundell** [comment]
Horses that can be ridden by people that aren't "height challenged" and aren't "of generous proportions" (how I hate politically correctness bullshit euphemisms!) would definitely be welcome.

Another horse related issue that might be worth looking at is to stop them from escaping their harnesses whenever spooked, as that's what caused me to give up trying to use horses altogether.

If a horse last position marker was used, it should be exactly that, rather than a GPS tracker using a GPS network that's no longer available.

**Comment by fairyarmadillo** [comment]
Can't little people ride dogs, and big people ride larger animals, like cows and moose?

Something I'd really love to see is for certain constructions (IE palisades) to require an animal or vehicle and some rope to help pull/lift parts into place. Imagine using a donkey, a tree, and a pulley to lift an engine block so you could fix it. That'd be sweet as hell.

**Comment by PatrikLundell** [comment]
Yes, tiny mutants can ride dogs (and with larger dogs they might be somewhat suitable for some small mutants as well). Neither cows nor moose are good for riding, with the cow back not being particularly suited for that kind of weight (although cows can be ridden, to some extent), and moose not working out well (king Carolus XII of Sweden tried to set up a moose riding regiment, but that experiment was eventually abandoned). Zebras have been used, but those are really nasty buggers that supposedly stand for the majority of zoo employee fatalities in the world.

Size DOES lock you out of using a mount, unless you're built like a scarecrow: the maximum carry weight of the game's ponies is 100 kg, and that's the total, i.e. including armor and anything else the rider (and horse) carries. This means that a horse can be used as a fairly poor beast of burden or be ridden by poorly equipped normal sized people or well equipped very small ones.

The obvious animal for large mutant riders is an elephant, but I doubt there are very many trained elephants available in New England, and quite possibly zero post apocalyptic mahouts.

**Comment by dchieh222** [comment]
I love horses and am familiar with them as a rider. Let me know if I can help.

**Comment by Procyonae** [comment]
> Horses that can be ridden by people that aren't "height challenged" and aren't "of generous proportions" (how I hate politically correctness bullshit euphemisms!) would definitely be welcome.

We're looking at adding realistic horse breeds, hopefully some breeds will handle lightly armoured tall peeps but numbers won't be skewed to make that happen, mutant horses would be where this could be addressed but I don't fancy tackling the lore/how things should become mutant side of mutant tame animals until there's precedent, especially regarding whether breeds should have mutant counterparts or whether they should just split into a few distinct variances "big mutant horse" vs "small mutant horse" etc just saying in their description that they're unrecognisable from their former breed or if all breeds some go on mutation but there should be different mutations etc

> If a horse last position marker was used, it should be exactly that, rather than a GPS tracker using a GPS network that's no longer available.

While I agree in principle if I add this which I'd like to I'll probably add the same magical nonsensical tracking we have for vehicles and NPCs you haven't even met yet, if someone wants to make a PR where the overhaul map knowledge then that would be cool but I'd rather make changes that fit the current state of the game and don't have much interest in making that change myself

**Comment by PatrikLundell** [comment]
I definitely agree with a focus on realistic horse breeds, with any mutant variants being added on top of that (and not in the first PR).

I'm not particularly familiar with horses, but there are ponies and normal riding school horses which should be reasonably common. There are also mini horses people use as pets, race horses (both for riding and for sitting in a silly cart behind it). On top of that there are work horses (that can be very large and very strong) and very occasional war horses (for people engaging in jousting and possibly reenactments). Horses used for jousting are capable of carry full sized people using extra protective jousting armor that's essentially useless for anything but jousting (but of as an extreme weight as some people think: the people involved don't have to be lifted onto the horses by cranes), and these horses are frequently equpped with barding (although the heaviest barding used historically would probably be very hard to come by without making it yourself).

**Comment by PatrikLundell** [comment]
I agree war horses are trained, not bred ready made. However, historically war horses were picked from the biggest and strongest of the horses available, and I would assume the same goes for the current day: someone with the money and interest to buy and train a war horse wouldn't just take the first riding horse they found, but would look for a suitable horse in what I would assume would be in a similar manner as to how you would look for horses suitable for other specialized purposes such as racing and jumping hurdles on a competition level, i.e. look for suitable characteristics both physically and mentally.
The aim of this rambling is to indicate that you'd have "normal" horses suitable for normal riding, as well as stronger ones suitable for riding in heavy gear and with some carrying capacity on top of that, so horses would come with different sizes and carrying capacities. I would assume most players would be more interested in total carrying capacity (including rider), than training to actually charge into battle with zombies, though.

**Comment by Armokorguest** [comment]
Yup, all that sounds pretty accurate and similar to our current plans.

**Comment by Procyonae** [comment]
Closing for now bc none of this is being actively worked on, we'll be back though 😉
