### ISSUE TITLE
Optimization Tracking Issue

### ISSUE THREAD

**Issue by prharvey** [CleverRaven/Cataclysm-DDA#70399]
### Is your feature request related to a problem? Please describe.

This is a tracking issue to cover a number of micro-optimizations I am in the process of making. On their own many of them would have limited effect, so this exists as a way to see the motivation for each of them, and why the sum is greater than the parts. These optimizations are focused around removing unnecessary virtual calls, branching, and non-inline calls.

There are quite a few hot functions in the game code that have a lot of juice left to squeeze when it comes to micro-optimizations. The main culprits are `int_id::int_id(const string_id&)`, `int_id::obj`, `maptile_at` and the various `has_flag()` methods on `Creature` and `map`. In fact, there are _at least_ two caches (reachability cache, pathfinding cache) in the codebase that only exists to paper over performance issues with these methods; these caches are not needed if the methods are simply faster. Removing these caches becomes important in a world where we want to increase the size of the reality bubble, as the cost of those caches scales with the size of that bubble.

e.g. removing the reachability cache is currently performance neutral, as the primary problem is now solved by reachability zones. This is what the flame graph of `sees` looks like with the cache removed (~20% of CPU is spent on this after my outstanding PRs are merged):
<img width="1006" alt="2lWFE7L" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/2677507/759c2226-e4a0-4fac-8176-78ce4e124c6f">

The vast majority of the CPU cost is not in the actual sees line check, but in flag checking and id resolution! This pattern repeats in other areas, e.g. field processing.

### Solution you would like.

The short list of work to do:

- [ ] 1. Statically remove virtual method bounds checking in `map` methods with `*_ib` types.
- [ ] 2. Remove unloaded submap checks in `map` by using a default null submap.
- [ ] 3. Remove uniform submap checks in `submap` by using a default initialized submap per terrain.
- [ ] 4. Remove z level branching in `nonant`.
- [ ] 5. Transform all static/stored `string_id`s into `int_id`s.
- [ ] 6. Remove linker magic for `int_id::obj()` and `int_id::is_valid()`; replace with traits.
- [ ] 7. Statically remove bounds checking in generic factory for int_ids.
- [ ] 8. De-virtualize `monster` flag checking by pushing it up to `Creature`.

### Additional context

Here is a godbolt link that shows what the before/after would look like for the map/submap changes: https://godbolt.org/z/x75js589s

Note that the changes reduce generated code 2-3x, and result in invariant lifting out of loops and chained calls (e.g. the expensive modulo/division).

**Comment by akrieger** [comment]
Can you expand on what you mean for #6 'removing linker magic'?

**Comment by prharvey** [comment]
> Can you expand on what you mean for #6 'removing linker magic'?

Users of `int_id<>` and `string_id<>` are required to implement these functions themselves, and the linker handles the resolution. e.g. `int_id<mtype>` requires it's own version of these functions. The majority of those are doing the same thing, and just forward to `generic_factory` functions. The problem with doing it this way is it moves function inlining for these incredibly cheap methods into link time optimization, which can be quite fragile in my experience.
