### ISSUE TITLE
Several keybinding menus missing redraws when closed

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#8514]
Version: 7994c6db24b631be2071bf0e66ac0168b19dd78b, ncurses

Closing the input manager (special keybinding menu) in certain places fails to clean up the screen, leaving some blackness.

Here are the affected screens:

- [x] Armor Soring menu: fixed in #16151.
- [x] Options menu: fixed in #16178.
- [x] Color management menu (available via <kbd>Esc</kbd> ><kbd>5</kbd>): fixed in #23050.
- [ ] Vehicle construction menu: reported in #9572, not fixed yet.
- [x] World Creation menu: fixed some time ago;
- [x] Character creation menu;
- [x] Factions menu: fixed in #16203;
- [ ] World Options and Finalize World in World Creation menu.

To reproduce, simply go to one of these menus, open the input manager with `?` and close it again and see what happens.
##

Edit by @Leland: updated list of screens and moved to checklist

**Comment by illi-kun** [comment]
Here is the list of affected menus:
- [x] Armor Soring menu: fixed in #16151.
- [x] Options menu: fixed in #16178.
- [ ] Color management menu (available via '?' -> '4'): not fixed yet;
- [ ] Character creation menu: not fixed yet (dedicated issue for this menu about the same glitch: #9835);
- [x] World Creation menu: fixed some time ago;
- [ ] Factions menu: not fixed yet;

Anything else, anyone?

**Comment by remyroy** [comment]
See this thread on the forum: http://smf.cataclysmdda.com/index.php?topic=12345.0

> The new update does indeed fix most of the refresh issues.

> However, I did still run into two refresh bugs when I tested the latest experimental:

> 1) The menu that pops up so you can choose what materials to use when crafting doesn't fully refresh when it disappears.

> 2) Vehicle headlights cause a black "box" to appear on screen when turned on, overhead lights don't seem to have this issue.

> Both issues went away when I set the console and map font values  to be the same, so it seems to be the same bug.

**Comment by illi-kun** [comment]
Thanks for note but it's not the same issue. Issue you described depends on used fonts (according to the last sentence in your quote) and the current issue is independent to any settings.

**Comment by Leland** [comment]
#14270 notes that this is an issue both from the character screen <kbd>@</kbd> and in the look screen <kbd>V</kbd>

**Comment by Night-Pryanik** [comment]
Tested on latest experimental as of September 27, 2019. Character creation menu redraws correctly (though I'm unsure which PR fixed it). Vehicle examine menu still has the issue.
